### ISSUE TITLE
DSCPCLASSIFY fails to start when built from source

### ISSUE THREAD

**Issue by hudra0** [jeverley/dscpclassify#16]
Just did a new custom build from OpenWrt Master branch and now DSCPCLASSIFY fails to start....

Probably the reason for this is because the Makefile hasn’t been updated after the main.nft split.

Makefile should probably be something like this:

```
	$(INSTALL_CONF) ./etc/config/dscpclassify $(1)/etc/config/
	$(INSTALL_CONF) ./etc/dscpclassify.d/main.nft $(1)/etc/dscpclassify.d/
	$(INSTALL_CONF) ./etc/dscpclassify.d/maps.nft $(1)/etc/dscpclassify.d/
	$(INSTALL_CONF) ./etc/dscpclassify.d/sets.nft $(1)/etc/dscpclassify.d/
	$(INSTALL_CONF) ./etc/dscpclassify.d/verdicts.nft $(1)/etc/dscpclassify.d/
	$(INSTALL_CONF) ./etc/hotplug.d/iface/21-dscpclassify $(1)/etc/hotplug.d/iface/
	$(INSTALL_BIN) ./etc/init.d/dscpclassify $(1)/etc/init.d/`
```

**Comment by jeverley** [comment]
Should now be fixed in in 0f1016a, a good reminder for me to ready this for pushing into the main package repository soon 🙂

**Comment by hudra0** [comment]
> a good reminder for me to ready this for pushing into the main package repository soon 🙂

Yea, this would be great.

**Comment by jeverley** [comment]
Will mark this particular issue as closed, but will track this as a feature request. 🙂
