### ISSUE TITLE
problem with startup on latest OpenWrt snapshot

### ISSUE THREAD

**Issue by trippleflux** [jeverley/dscpclassify#18]
```
root@router:/tmp# /etc/init.d/dscpclassify start
/etc/rc.common: line 394: can't create /tmp/etc/dscpclassify-pre.include: nonexistent directory
/etc/rc.common: line 394: can't create /tmp/etc/dscpclassify-pre.include: nonexistent directory
/etc/rc.common: line 394: can't create /tmp/etc/dscpclassify-pre.include: nonexistent directory
/etc/rc.common: line 394: can't create /tmp/etc/dscpclassify-pre.include: nonexistent directory
/etc/rc.common: line 394: can't create /tmp/etc/dscpclassify-pre.include: nonexistent directory
```

After editing /etc/init.d/dscpclassify : 
```
start_service() {
	mkdir /tmp/etc
	setup start || {
		log err "Service start failed"
		[ "$DEBUG" = 1 ] || cleanup
		return 1
	}
	log notice "Service started"
}
```
managed to start, but getting empty /tmp/etc

Also getting the following when starting : 
```
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
```
```
root@router:/tmp/etc# /etc/init.d/dscpclassify status
active with no instances
```

```
root@router:/tmp/etc# /etc/init.d/dscpclassify reload
The dscpclassify service does not appear to be loaded.
```

config file left as default vanilla.

Platform : x86_64

**Comment by jeverley** [comment]
Thanks for reporting these @trippleflux .

I've just pushed 84982a1 into the develop branch to handle the path and grep issues you've got with the latest snapshot.

The ```active with no instances``` message is to be expected as there is no discrete process running (it all lives within the kernel firewall tables).

The message ```The dscpclassify service does not appear to be loaded.``` is expected when you try and reload a service that isn't already started, there was an issue prior to https://github.com/jeverley/dscpclassify/commit/5e470255201a68c881a58cddf2ec145195bdae6a which was falsely making the check fail.

Possible to try the updated ```/etc/init.d/dscpclassify``` code in develop to see if it addresses your findings?

**Comment by trippleflux** [comment]
Thanks @jeverley , updated into ad03d9be0dc47f35e64b9eaf401018c323705af6 , no more error on startup and also enabled on boot, but how to really make sure dscpclassify is really running?, because using "ps -aux | grep dscp" return nothing, and also my /tmp/etc is still empty.

**Comment by jeverley** [comment]
Hi @trippleflux , there's no process that runs ass the logic lives within the firewall.

From command line you can see if it has loaded your rules using ```nft list table inet dscpclassify```.

By default the service will remove the temporary include files once it has started to save RAM, you can force it to keep these using the latest build in dev and setting 'debug' to '1' in the config file's global options (there's been some new commits today).

**Comment by jeverley** [comment]
The debug option is now available in main.

**Comment by trippleflux** [comment]
Thanks again @jeverley , now the nft table is populated on 5f6eebe6a6bfe74520b246d47c7e6e1861c9a16f .

Closing this issue.
