### ISSUE TITLE
fresh install quesion?

### ISSUE THREAD

**Issue by francisuk1989** [jeverley/dscpclassify#21]
Just a quick question on a fresh install of OpenWrt

Do you need anything eles installed like the following?

`opkg install sqm-scripts luci-app-sqm`

**Comment by jeverley** [comment]
Hi @francisuk1989 , apologies for the late reply.

Yes that command will include the necessary SQM components, I've now added to the readme the OpenWrt wiki link for setting up SQM as a pre-requisite.

**Comment by francisuk1989** [comment]
> Hi @francisuk1989 , apologies for the late reply.
> 
> Yes that command will include the necessary SQM components, I've now added to the readme the OpenWrt wiki link for setting up SQM as a pre-requisite.

Fantasic as i wasnt sure on that part.
