### ISSUE TITLE
Error with default config rules

### ISSUE THREAD

**Issue by Strasedon** [jeverley/dscpclassify#3]
With the default config there are errors when starting dscpclassify:

`user.notice dscpclassify: Rule contains an invalid port`

I think there are a couple of issues with check_port():

- I don't think the "+" needs escaped
- "\d" requires that the flag for Perl expressions needs to be used ("-P")
- If you choose to use that then you can't  you can't use multiple "-e" options in one grep invocation.

This seems to work fine, I changed to using extended grep for the character classes and keep the ability to use two "-e"s:

`check_port() {                                                                                                                                                              
        for i in $1; do                                                                                                                                                     
                echo "$i" | grep -q -E -e "^[[:digit:]]+-[[:digit:]]+$" -e "^[[:digit:]]+$"  || return 1                                                                    
        done                                                                                                                                                                
}   `

**Comment by jeverley** [comment]
Thanks for spotting this @Strasedon, I've tested your proposed change and it resolves the issue on my side too.
I'll merge this in shortly.
